analyses:
  - name: "chr21_centromere"
    fasta: "/research/hvw5426/splitted_fasta/chr21.fasta"
    start: 10962854
    length: 100000
    kmer: 20
    thresholds: [2, 4, 8, 16, 32, 64, 128]

  - name: "chr6_repeatmasker"
    fasta: "/research/hvw5426/splitted_fasta/chr6.fasta"
    start: 559707
    length: 100000
    kmer: 20
    thresholds: [2, 3, 4, 5, 6]