analyses:
  - name: "chr21_centromere"
    output_dir: "chr21_centromere"
    fasta: "../sequence_data/D-hardest.fasta"
    simulation_params:
      length: 100000
      start_pos: 0 #10962854
      precision: 1e-8
      replicates: 100
    plot_params:
      k_variation:
        thresholds: [32, 630]
        ylimits: [0.8, 0.02, 1.0] 
        fixed_r: 0.01 
      r_variation:
        threshold: 0.201
        fixed_k: 30
        