analyses:
  - name: "chr6_RepeatMasker_sketch_100"
    output_dir: "chr6_RepeatMasker_sketch_100"
    fasta: "/research/hvw5426/splitted_fasta/chr6.fasta"
    simulation_params:
      length: 100000
      start_pos: 559707
      precision: 1e-10
      replicates: 1
      sketch_repeats: 100 
    plot_params:
      theta_values: [0.1, 0.01] 
      k_variation:
        thresholds: [32, 570]
        ylimits: [0.8, 0.035, 1.1]
      r_variation:
        threshold: 0.151
        ylimits: [0.2, 1.1]

  - name: "chr21_centromere_sketch_100"
    output_dir: "chr21_centromere_sketch_100"
    fasta: "/research/hvw5426/splitted_fasta/chr21.fasta"
    simulation_params:
      length: 100000
      start_pos: 10962854
      precision: 1e-10
      sketch_repeats: 100  
    plot_params:
      theta_values: [0.1, 0.01]  
      k_variation:
        thresholds: [32, 570]
        ylimits: [0.8, 0.035, 1.1] 
      r_variation:
        threshold: 0.151
        ylimits: [0.2, 1.1]

