analyses:
  - name: "chr6_RepeatMasker"
    output_dir: "chr6_RepeatMasker"
    fasta: "/research/hvw5426/splitted_fasta/chr6.fasta"
    simulation_params:
      length: 100000
      start_pos: 559707
      precision: 1e-10
      replicates: 100
    plot_params:
      k_variation:
        thresholds: [32, 630]
        ylimits: [0.8, 0.02, 1.0] 
        fixed_r: 0.01 
      r_variation:
        threshold: 0.25
        fixed_k: 30

  - name: "chr21_centromere"
    output_dir: "chr21_centromere"
    fasta: "/research/hvw5426/splitted_fasta/chr21.fasta"
    simulation_params:
      length: 100000
      start_pos: 10962854
      precision: 1e-10
      replicates: 100
    plot_params:
      k_variation:
        thresholds: [32, 630]
        ylimits: [0.8, 0.05, 1.0] 
        fixed_r: 0.01
      r_variation:
        threshold: 0.25
        fixed_k: 30

  - name: "chrY_SimpleRepeat" # chrY:22420785-22423059,
    output_dir: "chrY_SimpleRepeat"
    fasta: "/research/hvw5426/splitted_fasta/chrY.fasta"
    simulation_params:
      length: 2264
      start_pos: 22420785
      precision: 1e-10
      replicates: 100
    plot_params:
      k_variation:
        thresholds: [32, 300]
        ylimits: [0.8, 0.02, 1.1]
        fixed_r: 0.01
      r_variation:
        threshold: 0.251
        fixed_k: 10